// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  badge1: string;
  badge2: string;
}
export const cssExports: CssExports;
export default cssExports;
