// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bodyWrapper: string;
  layoutFullFrame: string;
  layoutMainPageFrame: string;
  layoutSideSearchFrame: string;
  layoutTopFrame: string;
}
export const cssExports: CssExports;
export default cssExports;
