// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  input: string;
  navigator: string;
  right: string;
  searchbox: string;
}
export const cssExports: CssExports;
export default cssExports;
