// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'datetime': string;
  'item': string;
  'keyword': string;
  'path': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
